#Encoging
export MM_CHARSET=utf8
export LC_ALL=cs_CZ.UTF-8
export LANG=cs_CZ.UTF-8
export LANGUAGE=cs_CZ.UTF-8
#Main Editor
export EDITOR="nano"
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad
export GREP_OPTIONS='--color=auto'
#No mail checking
unset MAILCHECK
source $HOME/.prompt.sh


